[phases.setup]
nixPkgs = ["nodejs_20", "python311", "gcc", "gnumake", "pkg-config", "libusb1", "eudev"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --ignore-scripts || npm install --legacy-peer-deps --ignore-scripts"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
